[package]
name = "pyprint"
version = "1.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/su-z/pyprint.git"
description = "Library to enable python-style printing in rust"
readme = "README.md"

[lib]
name = "pyprint"
path = "src/lib.rs"

[dependencies]
